### ISSUE TITLE
raspbmirror.py - how to specify preferred mirror?

### ISSUE THREAD

**Issue by annuello** [plugwash/raspbian-tools#15]
I am trying to set up an internal mirror site in a somewhat firewall-restrictive environment.  My machine running the raspbmirror.py script has access to only archive.raspbian.org, mirrordirector.raspbian.org and one geographically-close mirror site.  The script spends considerable time trying to download from non-accessible mirrors which eventually times out and another server is attempted, but it becomes super-slow just waiting for timeouts to complete.  I think mirrordirector is suggesting a different geographically-close mirror, but alas my machine does not have access to that mirror.

How do I nominate/prioritise the mirror site that it can access?  I've tried using the baseurl and mdurl params to point the script to my preferred mirror, but that fails.

**Comment by plugwash** [comment]
You probablly want to point "baseurl" at archive.raspbian.org and "mdurl" at your local mirror.

Note that these urls should point one level above the apt repo. e.g http://archive.rasbian.org/ not http://archive.rasbian.org/raspbian

If you are still getting errors can you post the exact command you are trying?

**Comment by annuello** [comment]
Yeah, still having challenges.  Not sure what I'm doing wrong.  I'll be a bit verbose just so you have the full picture.  I have a 1Tb USB stick mounted and I'm running the script from there, with the intent to keep all mirror content on the USB stick.

```
/media/usb/raspbmirror.py
/media/usb/raspbian  <---- running commands from inside this directory
/media/usb/tmp
```

The various CLI iterations I've tried include:
`../raspbmirror.py --tmpdir ../tmp --distswhitelist bookworm`
Works sometimes, but subject to the whims of the redirector.  If I get redirected to a "firewall-allowed" mirror, all good.  If I get redirected to a mirror not on the firewall-allows list I get a 2min+ timeout and ultimately a fail.  Running a `netstat --numeric-ports` prior to the end of timeout, I can see it trying to connect (SYN_SENT) on port 80.  It tries several times - evident by a change in my server-side dynamic port for each connection attempt - before ultimately abandoning the attempt and giving the following error:
`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='baseurl=archive.raspbian.org', port=80): Max retries exceeded with url: /snapshotindex.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb1e0f410>: Failed to establish a new connection: [Errno -2] Name or service not known'))`



Next few attempt try various combinations of the two additional parameters.  All result in a "cli usage error".  Some permutations tried are as follows:
```
../raspbmirror.py --baseurl archive.raspbian.org --mdurl mirror.aarnet.edu.au --tmpdir ../tmp --distswhitelist bookworm
../raspbmirror.py --baseurl=archive.raspbian.org --mdurl=mirror.aarnet.edu.au --tmpdir ../tmp --distswhitelist bookworm
```

Having a read of the raspbmirror.py script it quickly becomes clear that the expected CLI format should not be double-dash for these two parameters.  I'm a Python novice, but I suspect there _may_ also be some order dependency with the parameters, so I'm sticking to the parameter order as found in raspbmirror.py.

Next attempt:
`../raspbmirror.py baseurl=archive.raspbian.org mdurl=mirror.aarnet.edu.au --tmpdir ../tmp --distswhitelist bookworm`
When running this one I get the following errors:
```
info: using urllib3
stage 1, scan existing
stage 2, main download
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8de0f410>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/usb/raspbian/../raspbmirror.py", line 540, in <module>
    (filedata,ts) = geturl(fileurl)
                    ^^^^^^^^^^^^^^^
  File "/media/usb/raspbian/../raspbmirror.py", line 171, in geturl
    response = dlmanager.request("GET", fileurl.decode('ascii'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 816, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 816, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 816, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='baseurl=archive.raspbian.org', port=80): Max retries exceeded with url: /snapshotindex.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de0f410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Adding http:// to the start of each site makes no difference - same error as above.  The mirror I'm attempting to use appears to support both https and http.

**Comment by plugwash** [comment]
baseurl, mdurl and hpurl are positional parameters. so you want.

    ../raspbmirror.py https://archive.raspbian.org/  http://mirror.aarnet.edu.au/pub/raspbian/ --tmpdir ../tmp --distswhitelist bookworm

**Comment by annuello** [comment]
Thank you.  I believe I'm getting closer to a working solution.
netstat shows connections being established to my mirror of choice - excellent.
Checking the file dates in my local repo, I can see that some files are getting updated, when compared to my previous run attempt.
```
touch --date "2025-09-01 00:00:00" ~/startDate
find /media/usb/raspbian -type f -newer ~/startDate
```


I'm hitting occasional issues which - as a newbie to repo mirroring - might just be part of the challenge of maintaining ones own repo copy.  Or perhaps it's a symptom of cached info from previous script-run attempts which did not succeed, and file versions in public repos have moved on since such attempts.
In Stage 3 (download final updates) the script:
- Attempts to download a file which appears to have been superseded by a newer version.
	-- Tries to download http://mirror.aarnet.edu.au/pub/raspbian//multiarch/pool/main/g/glibc/glibc_2.31-13+rpi1.debian.tar.xz
	-- Fails, since this appears to be superseded by glibc_2.36-9+rpi1.debian.tar.xz
- Attempts to download the same (older) version from archive.raspbian.org
	-- Tries to download https://archive.raspbian.org//multiarch/pool/main/g/glibc/glibc_2.31-13+rpi1.debian.tar.xz
	-- Fails since this file has also been superseded on archive.raspbian.org.
- Aborts after the failed download attempt from archive.raspbian.org  thus ending the script.

**Comment by plugwash** [comment]
Thanks, that was an issue on our end, with a data file which is only used by raspbmirror when running with the "distswhitelist" parameter and that wasn't getting updated.

I've updated it on the master server, it should push out to the public side in the next update run.

**Comment by annuello** [comment]
Success!  Today's run of the script got through to the end with no hiccups.

Thank you for your guidance and back-end fix.
